# Site settings
title: krystal
subtitle: 我热爱这个世界
keywords: krystal
description: 以自身的魅力，证明存在的价值！
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.liunian.org" # 你的域名
page_no_title: "krystal's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: krystal
email: jerry.caocc@liunian.org

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins_dir:
  - jekyll-paginate
  - jemoji
# gems:
#  - jekyll-coffeescript
#  - jekyll-watch
#  - jekyll-assets
gems: [jekyll-paginate]

# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook
  - page: 关于
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
links: # 友情链接
  - title: Jekyll blog system
    url: http://jekyllcn.com/

# Code hub settings
codehub: # 代码仓库
  - title: Github
    url: https://github.com/krystal-cao


#valine:
#  enable: true
#  app_id:  K1rbn2Oo0YMM04VuzdLS7Nzz-gzGzoHsz
#  app_key: AAsHbwVm8ofKFJ6ghGqqrXSU
#  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
#  verify: false # Verification code
#  visitor: true
#  avatar: retro
#  placeholder: say something~~\n - 昵称 为你所要显示的评论的ID；\n - 邮箱 只有后台可见，仅供讨论过程中是否需要交流邮件而设置，请放心填写;\n - 网址 为你的评论的昵称的超链接。\n当然，以上都可以不写，评论依然会显示……
#  guest_info: nick,mail,link
#  pageSize: 10

# Set which comment system to use
comments:
  # 'disqus' / 'giscus' / 'utterances' are available
  provider:            giscus
#https://github.com/mmistakes/minimal-mistakes/pull/3022#issuecomment-869022785:
# JEKYLL_ENV=production jekyll serve
  giscus:
    repo: oukohou/image_gallery
    repo_id:  MDEwOlJlcG9zaXRvcnkxODg5ODYzOTY=
    category: General
    category_id: DIC_kwDOC0O0HM4CdbSz
    mapping: pathname # optional, default to 'pathname'
    input_position: top# optional, default to 'bottom'
    lang: zh-CN# optional, default to the value of `site.lang`
    reactions_enabled: 1# optional, default to the value of `1`
